//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    
    [MetadataType(typeof(PROYECTOMetaData))]
    public partial  class PROYECTO
    {

    }

    public class PROYECTOMetaData
    {
        public System.Guid NROPROY { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public string NOMBRETIPOINV { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime FECHA { get; set; }
        [StringLength(150, ErrorMessage = "Este campo debe tener una longitud igual a 150.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [DataType(DataType.Text)]
        public string NOMBRE { get; set; }
        [StringLength(5000, ErrorMessage = "Este campo debe tener una longitud igual a 5000.")]
        [Required(ErrorMessage = "Este campo es requerido.")]
        [DataType(DataType.Text)]
        public string DESCRIPCION { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        [DataType(DataType.Currency)]
        public double PRESUPUESTO { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double PLAZO { get; set; }
        public string TIPOPLAZO { get; set; }
        public string TIPOPROYECTO { get; set; }
        public int NUMEROPERSONAS { get; set; }
        public string TIPODISENIOMUESTRAL { get; set; }
        public string SELECCIONALEATORIA { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double CONFIANZA { get; set; }
        public int NUMEROPARCELAS { get; set; }
        public int NUMEROPARCELASAMUESTREAR { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double TAMANIOPARCELA { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double AREATOTAL { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double INTMUESTREO { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double AREAMUESTREAR { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double LIMITINFDAP { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double AREAREGENERACION { get; set; }
        [Required(ErrorMessage = "Este campo es requerido.")]
        public double FACTORDEFORMA { get; set; }
        public int ETAPA { get; set; }
        public string CONFIGURACIONMAPA { get; set; }
    
    }
    
}
