//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOQUE
    {
        public System.Guid NROPROYCONTENEDOR { get; set; }
        public System.Guid NROPROYCONTENIDO { get; set; }
        public int CODIGOBLOQUE { get; set; }
        public double PESO { get; set; }
        public int ETAPA { get; set; }
        public string CONFIGURACIONMAPA { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
        public virtual PROYECTO PROYECTO1 { get; set; }
    }
}
