//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIGURACIONUNIDADMUESTRAL
    {
        public System.Guid NROCONFIGURACIONUNIDADMUESTRAL { get; set; }
        public System.Guid NROPROY { get; set; }
        public double ANCHO { get; set; }
        public double LARGO { get; set; }
        public double RADIO { get; set; }
        public string FORMA { get; set; }
        public string TIPOUNIDADMUESTRAL { get; set; }
    
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
