//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOMINIO
    {
        public DOMINIO()
        {
            this.VARIABLE = new HashSet<VARIABLE>();
        }
    
        public System.Guid NRODOMINIO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<VARIABLE> VARIABLE { get; set; }
    }
}
