//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULA
    {
        public FORMULA()
        {
            this.FORMULAVARIABLE = new HashSet<FORMULAVARIABLE>();
            this.PROYECTO = new HashSet<PROYECTO>();
        }
    
        public System.Guid NROFORMULA { get; set; }
        public System.Guid NROTIPOFORMULA { get; set; }
        public string EXPRESION { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual TIPOFORMULA TIPOFORMULA { get; set; }
        public virtual ICollection<FORMULAVARIABLE> FORMULAVARIABLE { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
    }
}
