//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO
    {
        public FORMULARIO()
        {
            this.LINEAINVENTARIO = new HashSet<LINEAINVENTARIO>();
        }
    
        public System.Guid NROFORMULARIO { get; set; }
        public int CODEST { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public System.Guid NROPROY { get; set; }
        public int CODIGOPARCELA { get; set; }
        public System.DateTime FECHACREACION { get; set; }
        public Nullable<System.DateTime> HORAINICIO { get; set; }
        public Nullable<System.DateTime> HORAFINAL { get; set; }
    
        public virtual ESTRATO ESTRATO { get; set; }
        public virtual ICollection<LINEAINVENTARIO> LINEAINVENTARIO { get; set; }
        public virtual PARCELA PARCELA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
