//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOCOMERCIAL
    {
        public GRUPOCOMERCIAL()
        {
            this.ESPECIE = new HashSet<ESPECIE>();
        }
    
        public string GRUPOCOM { get; set; }
        public string DESCRIPGRUPO { get; set; }
    
        public virtual ICollection<ESPECIE> ESPECIE { get; set; }
    }
}
