//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGEN
    {
        public System.Guid NROIMAGEN { get; set; }
        public System.Guid CODESP { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE { get; set; }
        public string RUTA { get; set; }
    
        public virtual ESPECIE ESPECIE { get; set; }
    }
}
