//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINEAINVENTARIOVARIABLE
    {
        public System.Guid NROVARIABLE { get; set; }
        public System.Guid LINEAINV { get; set; }
        public string VALOR { get; set; }
    
        public virtual LINEAINVENTARIO LINEAINVENTARIO { get; set; }
        public virtual VARIABLE VARIABLE { get; set; }
    }
}
