//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTADODEESTRATOS
    {
        public System.Guid NROPROY { get; set; }
        public int CODEST { get; set; }
        public Nullable<double> PESO { get; set; }
        public Nullable<double> TAMANIOMUESTRA { get; set; }
        public string CONFIGURACIONMAPA { get; set; }
    
        public virtual ESTRATO ESTRATO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
