//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTADODECOSTOS
    {
        public System.Guid NROCOSTO { get; set; }
        public System.Guid NROPROY { get; set; }
        public double VALOR { get; set; }
    
        public virtual COSTO COSTO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
