//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDAD
    {
        public LOCALIDAD()
        {
            this.LOCALIDAD1 = new HashSet<LOCALIDAD>();
            this.PROYECTO = new HashSet<PROYECTO>();
        }
    
        public int CODLOCALIDAD { get; set; }
        public Nullable<int> CODLOCALIDADPADRE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<LOCALIDAD> LOCALIDAD1 { get; set; }
        public virtual LOCALIDAD LOCALIDAD2 { get; set; }
        public virtual ICollection<PROYECTO> PROYECTO { get; set; }
    }
}
