//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARCELA
    {
        public PARCELA()
        {
            this.FORMULARIO = new HashSet<FORMULARIO>();
        }
    
        public System.Guid NROPROY { get; set; }
        public int CODIGOPARCELA { get; set; }
        public int LINEAPARCELA { get; set; }
        public string CONFIGURACIONMAPA { get; set; }
    
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
