//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        public PROYECTO()
        {
            this.BLOQUE = new HashSet<BLOQUE>();
            this.BLOQUE1 = new HashSet<BLOQUE>();
            this.CONFIGURACIONUNIDADMUESTRAL = new HashSet<CONFIGURACIONUNIDADMUESTRAL>();
            this.LISTADODECOSTOS = new HashSet<LISTADODECOSTOS>();
            this.LISTADODEESTRATOS = new HashSet<LISTADODEESTRATOS>();
            this.PARCELA = new HashSet<PARCELA>();
            this.FORMULA = new HashSet<FORMULA>();
            this.ESPECIE = new HashSet<ESPECIE>();
            this.LOCALIDAD = new HashSet<LOCALIDAD>();
            this.TIPOLINEAINVENTARIO = new HashSet<TIPOLINEAINVENTARIO>();
        }
    
        public System.Guid NROPROY { get; set; }
        public System.Guid NROUSUARIO { get; set; }
        public string NOMBRETIPOINV { get; set; }
        public System.DateTime FECHA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public double PRESUPUESTO { get; set; }
        public double PLAZO { get; set; }
        public string TIPOPLAZO { get; set; }
        public string TIPOPROYECTO { get; set; }
        public int NUMEROPERSONAS { get; set; }
        public string TIPODISENIOMUESTRAL { get; set; }
        public string SELECCIONALEATORIA { get; set; }
        public double CONFIANZA { get; set; }
        public int NUMEROPARCELAS { get; set; }
        public int NUMEROPARCELASAMUESTREAR { get; set; }
        public double TAMANIOPARCELA { get; set; }
        public double AREATOTAL { get; set; }
        public double INTMUESTREO { get; set; }
        public double AREAMUESTREAR { get; set; }
        public double LIMITINFDAP { get; set; }
        public double AREAREGENERACION { get; set; }
        public double FACTORDEFORMA { get; set; }
        public int ETAPA { get; set; }
        public string CONFIGURACIONMAPA { get; set; }
    
        public virtual ICollection<BLOQUE> BLOQUE { get; set; }
        public virtual ICollection<BLOQUE> BLOQUE1 { get; set; }
        public virtual ICollection<CONFIGURACIONUNIDADMUESTRAL> CONFIGURACIONUNIDADMUESTRAL { get; set; }
        public virtual ICollection<LISTADODECOSTOS> LISTADODECOSTOS { get; set; }
        public virtual ICollection<LISTADODEESTRATOS> LISTADODEESTRATOS { get; set; }
        public virtual OBJETIVOINVENTARIO OBJETIVOINVENTARIO { get; set; }
        public virtual ICollection<PARCELA> PARCELA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<FORMULA> FORMULA { get; set; }
        public virtual ICollection<ESPECIE> ESPECIE { get; set; }
        public virtual ICollection<LOCALIDAD> LOCALIDAD { get; set; }
        public virtual ICollection<TIPOLINEAINVENTARIO> TIPOLINEAINVENTARIO { get; set; }
    }
}
