//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLOQUE> BLOQUE { get; set; }
        public virtual DbSet<CONFIGURACIONUNIDADMUESTRAL> CONFIGURACIONUNIDADMUESTRAL { get; set; }
        public virtual DbSet<COSTO> COSTO { get; set; }
        public virtual DbSet<DOMINIO> DOMINIO { get; set; }
        public virtual DbSet<ESPECIE> ESPECIE { get; set; }
        public virtual DbSet<ESTRATO> ESTRATO { get; set; }
        public virtual DbSet<FORMULA> FORMULA { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIO { get; set; }
        public virtual DbSet<FORMULAVARIABLE> FORMULAVARIABLE { get; set; }
        public virtual DbSet<GRUPOCOMERCIAL> GRUPOCOMERCIAL { get; set; }
        public virtual DbSet<IMAGEN> IMAGEN { get; set; }
        public virtual DbSet<LINEAINVENTARIO> LINEAINVENTARIO { get; set; }
        public virtual DbSet<LINEAINVENTARIOVARIABLE> LINEAINVENTARIOVARIABLE { get; set; }
        public virtual DbSet<LISTADODECOSTOS> LISTADODECOSTOS { get; set; }
        public virtual DbSet<LISTADODEESTRATOS> LISTADODEESTRATOS { get; set; }
        public virtual DbSet<LOCALIDAD> LOCALIDAD { get; set; }
        public virtual DbSet<OBJETIVOINVENTARIO> OBJETIVOINVENTARIO { get; set; }
        public virtual DbSet<PARCELA> PARCELA { get; set; }
        public virtual DbSet<PROYECTO> PROYECTO { get; set; }
        public virtual DbSet<TIPOFORMULA> TIPOFORMULA { get; set; }
        public virtual DbSet<TIPOLINEAINVENTARIO> TIPOLINEAINVENTARIO { get; set; }
        public virtual DbSet<TSTUDENT> TSTUDENT { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<VARIABLE> VARIABLE { get; set; }
    }
}
