//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOFORMULA
    {
        public TIPOFORMULA()
        {
            this.FORMULA = new HashSet<FORMULA>();
        }
    
        public System.Guid NROTIPOFORMULA { get; set; }
        public string NOMBRETIPO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<FORMULA> FORMULA { get; set; }
    }
}
