//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFCA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIABLE
    {
        public VARIABLE()
        {
            this.FORMULAVARIABLE = new HashSet<FORMULAVARIABLE>();
            this.LINEAINVENTARIOVARIABLE = new HashSet<LINEAINVENTARIOVARIABLE>();
            this.DOMINIO = new HashSet<DOMINIO>();
            this.TIPOLINEAINVENTARIO = new HashSet<TIPOLINEAINVENTARIO>();
        }
    
        public System.Guid NROVARIABLE { get; set; }
        public string ABREVIATURA { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public string VARIABLEDESCRIPTIVA { get; set; }
        public string TIPODOMINIO { get; set; }
    
        public virtual ICollection<FORMULAVARIABLE> FORMULAVARIABLE { get; set; }
        public virtual ICollection<LINEAINVENTARIOVARIABLE> LINEAINVENTARIOVARIABLE { get; set; }
        public virtual ICollection<DOMINIO> DOMINIO { get; set; }
        public virtual ICollection<TIPOLINEAINVENTARIO> TIPOLINEAINVENTARIO { get; set; }
    }
}
